// Autogenerated
import Foundation
@testable import Harbor

struct SecureGetRequest: HGetRequestProtocol {
    typealias Model = TestSecureData

    var url: String { "https://secure.example.com/data" }
}

struct MTLSGetRequest: HGetRequestProtocol {
    typealias Model = TestSecureData

    var url: String { "https://mtls.example.com/data" }
}

struct FullySecureGetRequest: HGetRequestProtocol {
    typealias Model = TestSecureData

    var url: String { "https://fullysecure.example.com/data" }
}

struct TestDebugRequest: HGetRequestProtocol, HDebugRequestProtocol {
    typealias Model = MockModel

    let url: String = "https://api.example.com/test"
    var debugType: HDebugRequestType

    init(debugType: HDebugRequestType) {
        self.debugType = debugType
    }
}

struct TestStreamRequest: HGetRequestProtocol {
    typealias Model = TestStreamData

    let url: String = "https://stream.example.com/test"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestConfigRequest: HGetRequestProtocol {
    typealias Model = TestConfigData

    var url: String { "https://config.example.com/test" }
}

struct TestAuthenticatedConfigRequest: HGetRequestProtocol {
    typealias Model = TestConfigData

    var url: String { "https://config.example.com/auth-test" }
    var needsAuth: Bool { true }
}

struct TestFullyConfiguredRequest: HGetRequestProtocol {
    typealias Model = TestConfigData

    var url: String { "https://api.example.com/full-config-test" }
    var needsAuth: Bool { true }
    var headerParameters: [String: String]? {
        ["X-Custom-Header": "test-value"]
    }
}

struct GetUsersSimpleRequest: HGetRequestProtocol {
    typealias Model = TestUser
    let url = "https://api.example.com/users"
    // Uses default cacheType = .urlCache()
}

struct GetUsersWithCustomCacheRequest: HGetRequestProtocol {
    typealias Model = TestUser
    let url = "https://api.example.com/users"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration(expirationTime: .oneHour))
}

struct GetUsersNoCacheRequest: HGetRequestProtocol {
    typealias Model = TestUser
    let url = "https://api.example.com/users"
    let cacheType: HCache.CacheType? = .disabled
}

struct GetUsersCustomURLCacheRequest: HGetRequestProtocol {
    typealias Model = TestUser
    let url = "https://api.example.com/users"
    let cacheType: HCache.CacheType?

    init(urlCache: URLCache) {
        self.cacheType = .urlCache(urlCache: urlCache)
    }
}

struct GetUserRequest: HGetRequestProtocol {
    typealias Model = TestUser

    let userId: String

    var url: String { "https://api.example.com/users/\(userId)" }
}

struct CreateUserRequest: HPostRequestProtocol, @unchecked Sendable {
    typealias Model = TestUser

    let name: String
    let email: String
    var bodyParameters: [String: Any]?

    var url: String { "https://api.example.com/users" }

    init(name: String, email: String) {
        self.name = name
        self.email = email
        self.bodyParameters = ["name": name, "email": email]
    }
}

struct UploadFileRequest: HPostRequestProtocol, @unchecked Sendable {
    typealias Model = FileUploadResponse

    let fileName: String
    let fileData: Data
    var bodyParameters: [String: Any]? = nil
    var multipartBody: [String: HFormValue]?

    var url: String { "https://api.example.com/upload" }

    init(fileName: String, fileData: Data) {
        self.fileName = fileName
        self.fileData = fileData
        let fileURL = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString + "_" + fileName)
        try? fileData.write(to: fileURL)
        self.multipartBody = ["file": .file(url: fileURL, mimeType: nil, fileName: fileName), "filename": .text(fileName)]
    }
}

struct DeleteUserRequest: HDeleteRequestProtocol {
    let userId: String

    var url: String { "https://api.example.com/users/\(userId)" }
}

struct AuthenticatedRequest: HGetRequestProtocol {
    typealias Model = ProtectedData

    var url: String { "https://api.example.com/protected" }
    var needsAuth: Bool { true }
}

struct CustomHeadersRequest: HGetRequestProtocol {
    typealias Model = TestUser

    var url: String { "https://api.example.com/users/1" }
    var headerParameters: [String: String]? = [
        "X-API-Version": "v2",
        "Accept": "application/json",
        "User-Agent": "HarborTestClient/1.0"
    ]
}

struct GetUserByIdRequest: HGetRequestProtocol {
    typealias Model = TestUser

    let id: Int

    var url: String { "https://api.example.com/users/{id}" }
    var pathParameters: [String: String]? { ["id": "\(id)"] }
}

struct UpdateUserRequest: HPutRequestProtocol, @unchecked Sendable {
    let id: Int
    let name: String
    let email: String
    var bodyParameters: [String: Any]?

    var url: String { "https://api.example.com/users/\(id)" }

    init(id: Int, name: String, email: String) {
        self.id = id
        self.name = name
        self.email = email
        self.bodyParameters = ["name": name, "email": email]
    }
}

struct UpdateUserWithFileRequest: HPutRequestProtocol, @unchecked Sendable {
    typealias Model = TestUser

    let id: Int
    let name: String
    let fileData: Data
    var bodyParameters: [String: Any]? = nil
    var multipartBody: [String: HFormValue]?

    var url: String { "https://api.example.com/users/\(id)" }

    init(id: Int, name: String, avatar: Data) {
        self.id = id
        self.name = name
        self.fileData = avatar
        let fileURL = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString + "_avatar.jpg")
        try? fileData.write(to: fileURL)
        self.multipartBody = ["name": .text(name), "avatar": .file(url: fileURL, mimeType: nil, fileName: "avatar.jpg")]
    }
}

struct PartialUpdateUserRequest: HPatchRequestProtocol, @unchecked Sendable {
    let id: Int
    let name: String
    var bodyParameters: [String: Any]?

    var url: String { "https://api.example.com/users/\(id)" }

    init(id: Int, name: String) {
        self.id = id
        self.name = name
        self.bodyParameters = ["name": name]
    }
}

struct PartialUpdateUserWithJSONRequest: HPatchRequestProtocol, @unchecked Sendable {
    let id: Int
    let email: String
    var bodyParameters: [String: Any]?

    var url: String { "https://api.example.com/users/\(id)" }
    var bodyType: HRequestDataType { .json }

    init(id: Int, email: String) {
        self.id = id
        self.email = email
        self.bodyParameters = ["email": email]
    }
}

struct TimeoutRequest: HGetRequestProtocol {
    typealias Model = TestUser

    var url: String { "https://slow.example.com/timeout" }
}

struct ConnectionFailureRequest: HGetRequestProtocol {
    typealias Model = TestUser

    var url: String { "https://unreachable.example.com/data" }
}

struct InvalidHostRequest: HGetRequestProtocol {
    typealias Model = TestUser

    var url: String { "https://nonexistent.invalid.domain/data" }
}

struct MalformedRequest: HGetRequestProtocol {
    typealias Model = TestUser

    var url: String { "invalid-url-format" }
}

struct CancellableRequest: HGetRequestProtocol {
    typealias Model = TestUser

    var url: String { "https://api.example.com/slow-endpoint" }
}

struct StubbedGetRequest: HGetRequestProtocol {
    typealias Model = MockModel

    var url: String
    var retryPolicy: HRetryPolicy?
    var headerParameters: [String: String]?
    var needsAuth: Bool = false

    init(url: String, retryPolicy: HRetryPolicy? = nil, headerParameters: [String: String]? = nil, needsAuth: Bool = false) {
        self.url = url
        self.retryPolicy = retryPolicy
        self.headerParameters = headerParameters
        self.needsAuth = needsAuth
    }
}

struct HeaderlessAuthGetRequest: HGetRequestProtocol {
    typealias Model = MockModel

    var url: String { "https://example.com/secure" }
    var needsAuth: Bool { true }
}

struct TestDiskRequest: HGetRequestProtocol {
    typealias Model = TestDiskModel
    let url: String
    let cacheType: HCache.CacheType = .custom(HCache.Configuration())
}

struct TestCacheableRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/test"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestDefaultCacheableRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/non-cached"
    // cache defaults to nil (uses HConfig default)
}

struct TestCacheableGetRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/test"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
    let queryParameters: [String: String]? = ["page": "1", "limit": "10"]
}

struct TestCacheablePathRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/users/{userId}"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
    let pathParameters: [String: String]? = ["userId": "123"]
}

struct TestCustomExpirationRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/custom-expiration"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration(expirationTime: 60))
}

struct TestOneHourCacheRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/one-hour"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration(expirationTime: .oneHour))
}

struct TestExplicitlyDisabledRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/explicitly-disabled"
    let cacheType: HCache.CacheType? = .disabled
}

struct TestLongCacheRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    var url: String = "https://cache.example.com/long-test"
    var cacheType: HCache.CacheType? = .custom(HCache.Configuration(expirationTime: .oneHour)) // 1 hour
}

struct TestNoCacheRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/no-cache-test"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestZeroExpirationRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/zero-expiration"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration(expirationTime: 0))
}

struct TestNoStoreRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/no-store"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestLowercaseHeadersRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/lowercase-headers"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestVaryEnRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/vary"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
    var headerParameters: [String: String]? = ["Accept-Language": "en"]
}

struct TestVaryEsRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/vary"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
    var headerParameters: [String: String]? = ["Accept-Language": "es"]
}

struct TestRevalidationRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/revalidate"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestStaleOnErrorRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/stale-on-error"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestStaleOnErrorMustRevalidateRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/stale-on-error-must-revalidate"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestStaleOfflineRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/stale-offline"
    let cacheType: HCache.CacheType? = .custom(HCache.Configuration())
}

struct TestDedicatedURLCacheRequest: HGetRequestProtocol {
    typealias Model = TestCacheData

    let url: String = "https://cache.example.com/dedicated-url-cache"
    let cacheType: HCache.CacheType?

    init(urlCache: URLCache) {
        self.cacheType = .urlCache(urlCache: urlCache, requestCachePolicy: .reloadIgnoringLocalCacheData)
    }
}

struct TestEmptyResponseRequest: HRequestWithEmptyResponseProtocol {
    let url: String = "https://cache.example.com/empty-not-modified"
    var httpMethod: HHttpMethod { .get }
}


struct GetUsersRequest: HGetRequestProtocol {
    typealias Model = [TestUser]

    let page: Int
    let limit: Int

    var url: String { "https://api.example.com/users" }
    var queryParameters: [String: String]? {
        ["page": "\(page)", "limit": "\(limit)"]
    }
}
