// Autogenerated
import Foundation
@testable import Harbor

struct TestSecureData: HModel {
    let secret: String
}

struct TestStreamData: HModel {
    let value: String
    let timestamp: Date
}

struct TestConfigData: HModel {
    let value: String
}

struct TestUser: Codable, Sendable {
    let id: Int
    let name: String
    let email: String
}


struct FileUploadResponse: HModel {
    let id: String
    let url: String
}

struct ProtectedData: HModel {
    let secret: String
}

struct TestDiskEntry: Codable {
    let data: Data
    let timestamp: Date
    let expirationTime: TimeInterval?
}

struct TestDiskModel: HModel {
    let value: String

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        self.value = try container.decode(String.self)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(value)
    }
}

struct TestCacheData: HModel {
    let value: String
    let timestamp: Date
}

