import XCTest
import Harbor
@testable import HarborJRPC

@HRequestManagerActor
final class HarborJRPCTests: XCTestCase {

    override func setUp() async throws {
        await Harbor.removeAllMocks()
        await Harbor.setMocksOnlyInDebug(false)
        await HarborJRPC.configure(url: URL(string: "https://api.example.com/rpc")!, jrpcVersion: "2.0")
    }

    override func tearDown() async throws {
        await Harbor.removeAllMocks()
    }

    // MARK: - Body Construction

    func testBodyConstructionContainsJSONRPCMembers() async throws {
        // Given
        let request = TestRequest(method: "eth_blockNumber", requestID: .string("1"))

        // When
        let wrapper = request.wrapRequest(type: TestModel.self)
        let body = try XCTUnwrap(wrapper.bodyParameters)

        // Then
        XCTAssertEqual(body["jsonrpc"] as? String, "2.0")
        XCTAssertEqual(body["method"] as? String, "eth_blockNumber")
        XCTAssertEqual(body["id"] as? String, "1")
    }

    func testParamsKeyIsOmittedWhenParametersAreNil() async throws {
        // Given
        let request = TestRequest(method: "eth_blockNumber")

        // When
        let body = try XCTUnwrap(request.wrapRequest(type: TestModel.self).bodyParameters)

        // Then
        XCTAssertNil(body["params"])
    }

    func testNamedParametersSerializeAsJSONObject() async throws {
        // Given
        let request = TestRequest(method: "eth_getBalance", parameters: .named(["address": "0xabc", "block": "latest"]))

        // When
        let body = try XCTUnwrap(request.wrapRequest(type: TestModel.self).bodyParameters)
        let params = try XCTUnwrap(body["params"] as? [String: Any])

        // Then
        XCTAssertEqual(params["address"] as? String, "0xabc")
        XCTAssertEqual(params["block"] as? String, "latest")
    }

    func testPositionedParametersSerializeAsJSONArray() async throws {
        // Given
        let request = TestRequest(method: "eth_getBalance", parameters: .positioned(["0xabc", "latest"]))

        // When
        let body = try XCTUnwrap(request.wrapRequest(type: TestModel.self).bodyParameters)
        let params = try XCTUnwrap(body["params"] as? [Any])

        // Then
        XCTAssertEqual(params.count, 2)
        XCTAssertEqual(params[0] as? String, "0xabc")
        XCTAssertEqual(params[1] as? String, "latest")
    }

    func testAutoGeneratedIDIsAUUIDString() async throws {
        // Given
        let request = TestRequest(method: "eth_blockNumber")

        // When
        let body = try XCTUnwrap(request.wrapRequest(type: TestModel.self).bodyParameters)
        let id = try XCTUnwrap(body["id"] as? String)

        // Then
        XCTAssertNotNil(UUID(uuidString: id))
    }

    func testNotificationBodyHasNoID() async throws {
        // Given
        let request = TestNotificationRequest()

        // When
        let body = try XCTUnwrap(request.wrapRequest(type: TestModel.self).bodyParameters)

        // Then
        XCTAssertNil(body["id"])
        XCTAssertEqual(body["jsonrpc"] as? String, "2.0")
        XCTAssertEqual(body["method"] as? String, "eth_unsubscribe")
    }

    func testCustomNumericRequestIDAppearsInBody() async throws {
        // Given
        let request = TestRequest(method: "eth_blockNumber", requestID: .number(42))

        // When
        let wrapper = request.wrapRequest(type: TestModel.self)
        let body = try XCTUnwrap(wrapper.bodyParameters)

        // Then
        XCTAssertEqual(body["id"] as? Int, 42)
        XCTAssertEqual(wrapper.jrpcID, .number(42))
    }

    // MARK: - Notification

    func testNotifySucceedsAgainstMock() async throws {
        // Given
        let mock = HMock(request: HJRPCRequestWrapper<HJSONValue>.self, statusCode: 200, jsonResponse: "{}")
        await Harbor.register(mock: mock)

        // When / Then
        do {
            try await TestNotificationRequest().notify()
        } catch {
            XCTFail("Expected notify() to succeed but got: \(error)")
        }
    }

    func testNotifyOnNonNotificationRequestThrowsInvalidRequest() async throws {
        // Given
        let request = TestRequest(method: "eth_blockNumber")

        // When / Then
        do {
            try await request.notify()
            XCTFail("Expected notify() to throw")
        } catch let error as HJRPCRequestError {
            guard case .invalidRequest = error else {
                return XCTFail("Expected invalidRequest but got: \(error)")
            }
        }
    }

    // MARK: - Response Handling

    func testSuccessResponseDecodesModel() async throws {
        // Given
        let json = #"{"jsonrpc":"2.0","id":"1","result":{"value":"hello"}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        switch response {
        case .success(let model):
            XCTAssertEqual(model, TestModel(value: "hello"))
        case .error(let error):
            XCTFail("Expected success but got error: \(error)")
        }
    }

    func testCustomNumericRequestIDMatchesMockResponse() async throws {
        // Given
        let json = #"{"jsonrpc":"2.0","id":42,"result":{"value":"ok"}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .number(42)).requestResult()

        // Then
        switch response {
        case .success(let model):
            XCTAssertEqual(model, TestModel(value: "ok"))
        case .error(let error):
            XCTFail("Expected success but got error: \(error)")
        }
    }

    func testJRPCErrorResponseMapsToJRPCError() async throws {
        // Given
        let json = #"{"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"Method not found","data":{"reason":"unknown method"}}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        guard case .error(.jrpcError(let error)) = response else {
            return XCTFail("Expected jrpcError but got: \(response)")
        }
        XCTAssertEqual(error.code, -32601)
        XCTAssertEqual(error.message, "Method not found")
        XCTAssertEqual(error.data, .object(["reason": .string("unknown method")]))
    }

    func testEmptyURLReturnsURLNeeded() async throws {
        // Given
        HJRPCRequestManager.config.url = ""

        // When
        let response = await TestRequest(method: "test_method").requestResult()

        // Then
        guard case .error(.urlNeeded) = response else {
            return XCTFail("Expected urlNeeded but got: \(response)")
        }
    }

    func testMalformedResponseReturnsInvalidResponse() async throws {
        // Given
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: #"{"foo":"bar"}"#)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        guard case .error(.invalidResponse) = response else {
            return XCTFail("Expected invalidResponse but got: \(response)")
        }
    }

    func testResponseWithoutResultOrErrorReturnsInvalidResponse() async throws {
        // Given
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: #"{"jsonrpc":"2.0","id":"1"}"#)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        guard case .error(.invalidResponse) = response else {
            return XCTFail("Expected invalidResponse but got: \(response)")
        }
    }

    func testExplicitNullResultDecodesOptionalModel() async throws {
        // Given
        let mock = HMock(request: HJRPCRequestWrapper<Optional<String>>.self, statusCode: 200, jsonResponse: #"{"jsonrpc":"2.0","id":"1","result":null}"#)
        await Harbor.register(mock: mock)

        // When
        let response = await TestOptionalModelRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        switch response {
        case .success(let model):
            XCTAssertNil(model)
        case .error(let error):
            XCTFail("Expected success with nil model but got error: \(error)")
        }
    }

    func testMismatchedResponseIDReturnsIDMismatch() async throws {
        // Given
        let json = #"{"jsonrpc":"2.0","id":"2","result":{"value":"hello"}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        guard case .error(.idMismatch(let expected, let actual)) = response else {
            return XCTFail("Expected idMismatch but got: \(response)")
        }
        XCTAssertEqual(expected, .string("1"))
        XCTAssertEqual(actual, .string("2"))
    }

    func testWrongJRPCVersionReturnsInvalidResponse() async throws {
        // Given
        let json = #"{"jsonrpc":"1.0","id":"1","result":{"value":"hello"}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When
        let response = await TestRequest(method: "test_method", requestID: .string("1")).requestResult()

        // Then
        guard case .error(.invalidResponse) = response else {
            return XCTFail("Expected invalidResponse but got: \(response)")
        }
    }

    // MARK: - Throwing Request

    func testThrowingRequestReturnsModelOnSuccess() async throws {
        // Given
        let json = #"{"jsonrpc":"2.0","id":"1","result":{"value":"hello"}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When
        let model = try await TestRequest(method: "test_method", requestID: .string("1")).request()

        // Then
        XCTAssertEqual(model, TestModel(value: "hello"))
    }

    func testThrowingRequestThrowsOnJRPCError() async throws {
        // Given
        let json = #"{"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"Method not found"}}"#
        let mock = HMock(request: HJRPCRequestWrapper<TestModel>.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        // When / Then
        do {
            _ = try await TestRequest(method: "test_method", requestID: .string("1")).request()
            XCTFail("Expected request() to throw")
        } catch let error as HJRPCRequestError {
            guard case .jrpcError(let jrpcError) = error else {
                return XCTFail("Expected jrpcError but got: \(error)")
            }
            XCTAssertEqual(jrpcError.code, -32601)
        }
    }

    // MARK: - Batch

    func testBatchMapsEnvelopesToResponses() async throws {
        // Given
        let json = #"[{"jsonrpc":"2.0","id":"1","result":"0x1"},{"jsonrpc":"2.0","id":"2","result":"0x2"},{"jsonrpc":"2.0","id":"3","error":{"code":-32602,"message":"Invalid params"}}]"#
        let mock = HMock(request: HJRPCBatchWrapper.self, statusCode: 200, jsonResponse: json)
        await Harbor.register(mock: mock)

        let requests: [any HJRPCRequestProtocol] = [
            TestStringRequest(method: "eth_blockNumber", requestID: .string("1")),
            TestStringRequest(method: "eth_chainId", requestID: .string("2")),
            TestStringRequest(method: "eth_getBalance", requestID: .string("3")),
        ]

        // When
        let responses = await HarborJRPC.batch(requests)

        // Then
        XCTAssertEqual(responses.count, 3)

        guard case .success(let firstID, let firstResult) = responses[0] else {
            return XCTFail("Expected success but got: \(responses[0])")
        }
        XCTAssertEqual(firstID, .string("1"))
        XCTAssertEqual(firstResult, .string("0x1"))

        guard case .success(let secondID, let secondResult) = responses[1] else {
            return XCTFail("Expected success but got: \(responses[1])")
        }
        XCTAssertEqual(secondID, .string("2"))
        XCTAssertEqual(secondResult, .string("0x2"))

        guard case .error(let thirdID, let thirdError) = responses[2] else {
            return XCTFail("Expected error but got: \(responses[2])")
        }
        XCTAssertEqual(thirdID, .string("3"))
        guard case .jrpcError(let jrpcError) = thirdError else {
            return XCTFail("Expected jrpcError but got: \(thirdError)")
        }
        XCTAssertEqual(jrpcError.code, -32602)
    }

    func testBatchWithEmptyURLReturnsURLNeededPerRequest() async throws {
        // Given
        HJRPCRequestManager.config.url = ""

        let requests: [any HJRPCRequestProtocol] = [
            TestStringRequest(method: "eth_blockNumber", requestID: .string("1")),
            TestStringRequest(method: "eth_chainId", requestID: .string("2")),
        ]

        // When
        let responses = await HarborJRPC.batch(requests)

        // Then
        XCTAssertEqual(responses.count, 2)
        for (index, response) in responses.enumerated() {
            guard case .error(let id, let error) = response else {
                return XCTFail("Expected error but got: \(response)")
            }
            XCTAssertEqual(id, .string("\(index + 1)"))
            guard case .urlNeeded = error else {
                return XCTFail("Expected urlNeeded but got: \(error)")
            }
        }
    }

    // MARK: - HJRPCId

    func testHJRPCIdDecoding() async throws {
        let decoder = JSONDecoder()

        XCTAssertEqual(try decoder.decode(HJRPCId.self, from: Data(#""abc""#.utf8)), .string("abc"))
        XCTAssertEqual(try decoder.decode(HJRPCId.self, from: Data("42".utf8)), .number(42))
        XCTAssertEqual(try decoder.decode(HJRPCId.self, from: Data("null".utf8)), .null)
    }

    // MARK: - Standard Codes

    func testStandardCodesAndServerErrorRange() async {
        XCTAssertEqual(HJRPCError(code: -32601, message: "x").standardCode, .methodNotFound)
        XCTAssertTrue(HJRPCError(code: -32601, message: "x").isStandard)
        XCTAssertNil(HJRPCError(code: 500, message: "x").standardCode)
        XCTAssertFalse(HJRPCError(code: 500, message: "x").isStandard)

        XCTAssertTrue(HJRPCError(code: -32000, message: "x").isServerError)
        XCTAssertTrue(HJRPCError(code: -32099, message: "x").isServerError)
        XCTAssertFalse(HJRPCError(code: -32601, message: "x").isServerError)
    }

    // MARK: - LocalizedError

    func testJRPCErrorLocalizedDescriptionContainsCodeAndMessage() async {
        let error = HJRPCRequestError.jrpcError(error: HJRPCError(code: -32601, message: "Method not found"))

        XCTAssertTrue(error.localizedDescription.contains("-32601"))
        XCTAssertTrue(error.localizedDescription.contains("Method not found"))
    }

    // MARK: - Configuration

    func testSetURLFromStringValidatesTheURL() async throws {
        do {
            try await HarborJRPC.setURL("https://api.example.com/rpc")
        } catch {
            XCTFail("Expected setURL to succeed but got: \(error)")
        }

        do {
            try await HarborJRPC.setURL("ht tp://bad url")
            XCTFail("Expected setURL to throw")
        } catch let error as HJRPCConfigurationError {
            guard case .invalidURL(let urlString) = error else {
                return XCTFail("Expected invalidURL but got: \(error)")
            }
            XCTAssertEqual(urlString, "ht tp://bad url")
        }
    }

    func testHJRPCConfigPublicInit() async {
        let config = HJRPCConfig(url: "https://api.example.com/rpc", jrpcVersion: "2.0")

        XCTAssertEqual(config.url, "https://api.example.com/rpc")
        XCTAssertEqual(config.jrpcVersion, "2.0")

        let defaultConfig = HJRPCConfig()
        XCTAssertEqual(defaultConfig.url, "")
        XCTAssertEqual(defaultConfig.jrpcVersion, "2.0")
    }

    // MARK: - HJRPCResponse

    func testHJRPCResponseDescription() async {
        let success = HJRPCResponse<TestModel>.success(TestModel(value: "hello"))
        XCTAssertTrue(success.description.contains("success"))

        let error = HJRPCResponse<TestModel>.error(.urlNeeded)
        XCTAssertTrue(error.description.contains("error"))
    }
}

// MARK: - Test Helpers

private struct TestModel: HModel, Equatable {
    let value: String
}

private struct TestRequest: HJRPCRequestProtocol {
    typealias Model = TestModel

    let method: String
    let parameters: HJRPCParams?
    let requestID: HJRPCId?

    init(method: String, parameters: HJRPCParams? = nil, requestID: HJRPCId? = nil) {
        self.method = method
        self.parameters = parameters
        self.requestID = requestID
    }
}

private struct TestNotificationRequest: HJRPCRequestProtocol {
    typealias Model = TestModel

    let method: String = "eth_unsubscribe"
    let isNotification: Bool = true
}

private struct TestOptionalModelRequest: HJRPCRequestProtocol {
    typealias Model = String?

    let method: String
    let requestID: HJRPCId?
}

private struct TestStringRequest: HJRPCRequestProtocol {
    typealias Model = String

    let method: String
    let requestID: HJRPCId?
}
