name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install CocoaPods
      run: gem install cocoapods
    - name: Deploy to CocoaPods
      run: pod trunk push Harbor.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
